spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      
  kafka:
    bootstrap-servers: localhost:9092
    
  redis:
    host: localhost
    port: 6379
    
  sleuth:
    sampler:
      probability: 1.0 # Activer la traçabilité pour toutes les requêtes
      
  zipkin:
    base-url: http://localhost:9411 # URL de Zipkin
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
  metrics:
    export:
      prometheus:
        enabled: true